### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by mehulkar** [blessanm86/tweet-to-html#19]
Is there a build process for this package before publishing?

I see `browserify` in the package script: https://github.com/blessanm86/tweet-to-html/blob/a4de37155dac4c57ea21ba1c90fec4e64772b384/package.json#L8

and a reference to parcel in the gitignore: https://github.com/blessanm86/tweet-to-html/blob/a4de37155dac4c57ea21ba1c90fec4e64772b384/.gitignore#L3

but neither are dependencies, so I'm not sure if it's being used. 

Would you be interested in setting something up? (esbuild/swc/etc). Couple motivations:

- Transpiling purposes, so we can use `const`/`let` and continue to have support for older environments if you want that (although if that's not important, maybe we don't need to transpile anything)
- For #17, I was thinking it might be worthwhile to add another module that makes requests to the API as well (using [`twitter-api-sdk`](https://github.com/twitterdev/twitter-api-typescript-sdk#readme). In that case, transpiling may be more important if we want to use fetch, async/await, etc
- Browser vs node usage. I am using this in Vercel's serverless functions, so I only care about Node, but if you want this to run in a browser also, there may be more use cases for transpiling, as well as minification.

**Comment by blessanm86** [comment]
The build command is for the demo site. Atm its using github pages and its using the `gh-pages` branch for that. I do want to get rid of that branch and put everything in master and use netlify instead.

I think in one of the last commits i just moved the demo folder to master branch and tried replacing browserify with parcel. After I merged ur pr I tried updating the demo site and noticed like quoted tweets dont render properly so I parked it.

But ya to answer ur question, im not opposed to a build step. Doesn't parcel just use swc under the hood. We could use that.

**Comment by blessanm86** [comment]
I have pushed some changes to master. Like i moved the demo site. U can run it with `npm run demo`. Its still show v1 tweet objects.

Also added parcel to build the lib. So I believe it now support for CJS and ESM and should take care of all the transpiling. I haven't really tested it out though. U can see the changes in my last commit.

**Comment by mehulkar** [comment]
Closing this out since i"m not using this lib much anymore!
