### ISSUE TITLE
twitter-text lib

### ISSUE THREAD

**Issue by mehulkar** [blessanm86/tweet-to-html#20]
I just found https://github.com/twitter/twitter-text/tree/master/js. Just pointing it out here. If it works all right for me, I'm happy to contribute this a change to this package to leverage that library instead (or just close my issues/PRs and revert the merged change)

**Comment by blessanm86** [comment]
I did notice this library sometime ago didn't try it out. So not really sure how to use it. But ya im all up for replacing any of the existing code with this package given its an official parser/tokenizer.

**Comment by mehulkar** [comment]
Closing this out since i"m not using this lib much anymore!
